// <auto-generated />
using System;
using CrashCourseServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrashCourseServer.Migrations
{
    [DbContext(typeof(EntryDbContext))]
    [Migration("20181201023450_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrashCourseServer.Models.Entry", b =>
                {
                    b.Property<int>("id");

                    b.Property<double>("bodyFat");

                    b.Property<DateTime>("date");

                    b.Property<int>("weight");

                    b.HasKey("id");

                    b.ToTable("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
